name: Vue CI with Vite

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Compress dist folder
        run: tar -czf dist.tar.gz dist
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-tar
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-tar
          path: .
      - name: Cleanup old dist archive on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: rm -f /tmp/dist.tar.gz

      - name: Upload dist archive to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist.tar.gz"
          target: "/tmp"
      - name: Extract dist archive on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/html/*
            tar -xzf /tmp/dist.tar.gz -C /var/www/html --strip-components=1